# Generated by Django 6.0.3 on 2026-03-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
