services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cinereserve-backend:local
    container_name: cinereserve-backend
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
      CELERY_BROKER_URL: redis://redis:6379/3
      CELERY_RESULT_BACKEND: redis://redis:6379/4
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    image: cinereserve-backend:local
    container_name: cinereserve-worker
    command:
      [
        "/app/.venv/bin/celery",
        "-A",
        "core",
        "worker",
        "-l",
        "info"
      ]
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
      CELERY_BROKER_URL: redis://redis:6379/3
      CELERY_RESULT_BACKEND: redis://redis:6379/4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  beat:
    image: cinereserve-backend:local
    container_name: cinereserve-beat
    command:
      [
        "/app/.venv/bin/celery",
        "-A",
        "core",
        "beat",
        "-l",
        "info"
      ]
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      REDIS_URL: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
      CELERY_BROKER_URL: redis://redis:6379/3
      CELERY_RESULT_BACKEND: redis://redis:6379/4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:18.3-alpine
    container_name: cinereserve-db
    environment:
      POSTGRES_DB: cinereserve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinereserve"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    container_name: cinereserve-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:
